<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE businessCard
[
    <!ELEMENT businessCard (person+)>
    <!ELEMENT person (name, number+, email)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT number (#PCDATA)>
    <!ATTLIST number type (home|work|mobile) #REQUIRED>
    <!ELEMENT email (#PCDATA)>

]>

<businessCard>

    <person>
        <name>Rorie Demanche</name>
        <number type="home">+1(710)153-4949</number>
        <number type="work">+1(503)319-3558</number>
        <number type="mobile">+1(182)748-1667</number>
        <email>rdemanche0@fornews.com</email>
    </person>

    <person>
        <name>Kelcey Surman</name>
        <number type="home">+1(249)926-7376</number>
        <number type="work">+1(208)363-6588</number>
        <number type="mobile">+1(982)536-6860</number>
        <email>ksurman0@usnews.com</email>
    </person>

    <person>
        <name>Simon Heddan</name>
        <number type="home">+1(687)808-4290</number>
        <number type="work">+1(604)815-7810</number>
        <number type="mobile">+1(924)174-3271</number>
        <email>sheddan2@alexa.com</email>
    </person>

    <person>
        <name>Chan Supple</name>
        <number type="home">+1(577)165-2495</number>
        <number type="work">+1(547)934-7337</number>
        <number type="mobile">+1(367)667-0747</number>
        <email>csupple3@123-reg.co.uk.com</email>
    </person>

</businessCard>